FROM node:20.10.0

WORKDIR /file
COPY ./frontend .

COPY ./exec/env/.env_frontend .env
RUN echo "src" > .eslintignore \
    && echo "srcsrc" >> .eslintignore

RUN npm install
RUN npm run build

CMD ["bash"]

